version: '2'
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    security_opt:
     - seccomp:unconfined
    ports:
     - "3000:3000"
  api:
    build: ./api
    volumes:
      - ./api:/api
    security_opt:
     - seccomp:unconfined
    ports:
     - "3001:3001"