version: '2'
services:
  app:
    working_dir: /app
    image: node
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    security_opt:
     - seccomp:unconfined
    entrypoint: bash -c "npm install --only=production && npm run prod"
    ports:
     - "3000:3000"
  api:
    build: ./api
    working_dir: /api
    volumes:
      - ./api:/api
      - ./api/node_modules:/api/node_modules
      - ./input_files:/input_files
    security_opt:
     - seccomp:unconfined
    entrypoint: bash -c "npm install --only=production && npm start"
    ports:
     - "3001:3001"